#!/usr/bin/python3

import socket
import sys
import json

BUF_SIZE = 4096


class Client:

    sc = None

    def trivial(self, line: str):
        res = self.send(line)
        print(res["message"])

    def exit(self):
        self.sc.close()
        exit()

    def consume(self, line: str):
        line = line.strip()
        if len(line) == 0:
            return

        command = line.split()[0]
        if command == 'exit':
            self.exit()
        else:
            self.trivial(line)

    def send(self, message: str):
        self.sc.send(message.encode('utf-8'))
        msg, _ = self.sc.recvfrom(BUF_SIZE)
        msg = msg.decode('utf-8')
        msg = json.loads(msg)
        return msg

    def run(self):
        while True:
            line = input("% ")
            self.consume(line)

    def __init__(self, sc: socket.socket):
        self.sc = sc


def main():

    if len(sys.argv) != 3:
        print("Usage: client <address> <port>")
        exit(-1)

    addr = sys.argv[1]
    port = int(sys.argv[2])

    tcpSocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    tcpSocket.connect((addr, port))

    welcome = """********************************
** Welcome to the BBS server. **
********************************"""
    print(welcome)

    client = Client(tcpSocket)
    client.run()


if __name__ == "__main__":
    main()
